apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: argo-events
spec:
  destination:
    namespace: events
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-events
    helm:
      values: |
        "singleNamespace": false
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 1.7.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
