apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflow-templates
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: templates
    repoURL: https://github.com/apirator/workflow-definitions.git
    targetRevision: HEAD
  destination:
    namespace: events
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true