apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflow-events
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: events
    repoURL: https://github.com/apirator/workflow-definitions.git
    targetRevision: HEAD
  destination:
    namespace: events
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
