apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: players-v2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: stable/players
    repoURL: https://github.com/claudioed/bets-helm.git
    targetRevision: players-v2
  destination:
    namespace: bets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
