apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mocks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mocks
  source:
    path: mocks
    repoURL: https://github.com/apirator/workflow-manifests.git
    targetRevision: HEAD
  destination:
    namespace: mocks
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true