apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kong
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Kong Project
  sourceRepos:
    - https://charts.konghq.com
  destinations:
    - namespace: kong
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
