apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: APIs Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: apis
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'