apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mocks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Mocks Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: mocks
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'