apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      version: v3
      parameters:
        - name: ingressController.installCRDs
          value: "false"
#        - name: proxy.type
#          value: "NodePort"
    chart: kong
    repoURL: https://charts.konghq.com
    targetRevision: 2.2.0
  destination:
    namespace: kong
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
